### ISSUE TITLE
PropertyEnumによるtypeとfacingの値の計算がうまくいかない

### ISSUE THREAD

**Issue by RiSE4** [RiSE4/CocricotLite#1]
rise.cocricotlite.block.dish.BlockCoffee内でgetStateFromMeta()とgetMetaFromState()におけるメタデータの計算がうまくい来ません。
これのせいでワールドを再読み込みした時に全ブロックが北方向を向いてしまいます。
他のブロックもそうですがとりあえずBlockCoffeeだけをいじって試行錯誤しています。

**Comment by Hiroya-W** [comment]
ワールド保存時には、ブロックのIBlockStateで保存、ワールド読み込み時にはIBlockStateからmetaを取り出して、ブロックにmetaを適用する
ってことでいいんかな...?

singleとdoubleって異なるブロックなってるん？metaを変えてブロックの種類変えてるん？

**Comment by RiSE4** [comment]
詳しく言うとちょっと違うらしいんですけどその解釈でいいと思います。
singleとdoubleはPropertyEnumってのを使ってmeta経由でブロックの種類変えてます。
羊毛とかみたいな感じです。rise.cocricotlite.util.typeの中にEnumはあります。
