### ISSUE TITLE
メタデータの計算(4bit AND)がうまくいかない

### ISSUE THREAD

**Issue by RiSE4** [RiSE4/CocricotLite#4]
rise.cocricotlite.block.nature.BlockWindowBoxにおいて、BlockCoffeeの時やったようにメタの計算を行いました。ロード時には適切なメタが振り分けられているようですが、(ログで確認した)
設置時に24や96といったありえない数値が計算されます。
「3,4桁をANDすればいいのでは？」と思ったのでgetStateFromMetaのANDを4から12にしてみましたが、うまくいきません。

**Comment by Hiroya-W** [comment]
方針はOKでした
シフト演算と算術演算を同時にやるところでバグらせてます
気をつけたいところですが、**シフト演算は算術演算より優先度が低いです**
先に`2+horizontal`が評価され、その後でシフト演算されます

ここを
```
meta = meta << 2 + horizontal;
```

こうすればOKです
```
meta = (meta << 2) + horizontal;
```

**Comment by RiSE4** [comment]
教えてもらったシフト演算に書き換えてやってみようとしたのがアダになったようです。
優先度があるのは知りませんでした。よく見るとgetStateForMetaの
中ではちゃんと()してあるんですね。ありがとうございます！
